### ISSUE TITLE
perfomance issue

### ISSUE THREAD

**Issue by smirnov-vs** [bingmann/stx-btree#3]
inline bool key_lessequal(const key_type& a, const key_type b) const
inline bool key_greaterequal(const key_type& a, const key_type b) const

passing b by value significantly decreases performance

**Comment by bingmann** [comment]
fixed mistake in f27df4c7b6a7a776390ec2825dcfc1547bddb714
However, because compilers will optimize these things, this should have no impact on optimized code.
