### ISSUE TITLE
Condition set permanently to false

### ISSUE THREAD

**Issue by gallushi** [bingmann/stx-btree#5]
In the following line, the condition is always `false`, thus linear search is always performed.
Is it on purpose?

https://github.com/bingmann/stx-btree/blob/f27df4c7b6a7a776390ec2825dcfc1547bddb714/include/stx/btree.h#L1636

**Comment by bingmann** [comment]
The reason is this:
https://panthema.net/2013/0504-STX-B+Tree-Binary-vs-Linear-Search/
